### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/resolve-pkg#2]
Is there a CLI version of this?

**Comment by sindresorhus** [comment]
Does https://github.com/sindresorhus/pkg-dir-cli solve your needs?

**Comment by fregante** [comment]
Kind of, but I'm using two more commands to get from `xo` to `/usr/local/lib/node_modules/xo` (i.e. `which` and `realpath`)

**Comment by sindresorhus** [comment]
@bfred-it What problem are you trying to solve? Maybe I can help guide you in the correct direction.

**Comment by fregante** [comment]
https://github.com/bfred-it/bin-dir

Edit: I was building it as a shell script and actually now it's a js file, so technically I don't need this anymore.
